- menu_name: "Contatti"

- name: "Mail"
  url: "mailto:giorgio.gambosi@uniroma2.it?&subject=Corso%20Fondamenti%20di%20Informatica"
  title: "Mail"
  
- name: "Teams"
  url: "https://teams.microsoft.com/l/team/19%3aTtzlHmWr5eGD-az0mxfwkruAItmXv1FkjRdncnke2wY1%40thread.tacv2/conversations?groupId=de377fb7-e5eb-4205-8201-f32a8dedb3f6&tenantId=24c5be2a-d764-40c5-9975-82d08ae47d0e"
  title: "Teams"

#- name: "Twitter"
#  url: "twitter.com/tvmlclass"
#  title: "Twitter"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"